spring.datasource.url=jdbc:mysql://localhost:3308/food_ordering_system_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=R00t@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
