spring.application.name=food-ordering-system
spring.profiles.active=dev

api.base.path=/api/v1

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.hibernate.naming.physical-strategy=org._p1m.foodorderingsystem.common.jpa.PluralPhysicalNamingStrategy

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/structure,classpath:db/migration/data
spring.flyway.validate-on-migrate=true
spring.flyway.default-schema=food_ordering_system_db

app.storage.type=CLOUDINARY
CLOUDINARY_CLOUD_NAME=dsylx9zse
CLOUDINARY_API_KEY=323724637428716
CLOUDINARY_API_SECRET=ObkjrGOodGjUiw2IFLjCEPJOksE