spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering_system_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1223
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minzayarmaung2002@gmail.com
spring.mail.password=vgklvkranagneybo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

#Flyway_log
logging.level.org.flywaydb=INFO
jwt.secret=ZP4g8Nj6QbXWYr2NvG2kXsKcD1HLqEyV

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379