spring.application.name=food-ordering-system
spring.profiles.active=dev

api.base.path=/api/v1

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.naming.physical-strategy=org._p1m.foodorderingsystem.common.jpa.PluralPhysicalNamingStrategy