apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "food-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
