name: Build Java App

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for Gradle
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      # if gradle has new dependencies installed generate the new cache key
      - name: Generate Gradle Cache Key
        id: gradle-cache-key
        run: |
          echo "key=gradle-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/settings.gradle.kts') }}" >> "$GITHUB_OUTPUT"

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.gradle-cache-key.outputs.key }}
          restore-keys: |
            gradle-

      - name: Build the app
        run: ./gradlew clean assemble --no-daemon

      - name: Run Flyway Validate
        run: ./gradlew flywayValidate


#name: Build Java App
#
#on:
#  workflow_call:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    outputs:
#      cache-hit: ${{ steps.cache.outputs.cache-hit }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set Up Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'corretto'
#          java-version: '17'
#
#      - name: Grant execute permission for Gradle
#        if: runner.os != 'Windows'
#        run: chmod +x ./gradlew
#
# # if gradle has new dependencies installed generate the new cache key
#      - name: Generate Gradle Cache Key
#        id: gradle-cache-key
#        run: |
#            echo "key=gradle-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/settings.gradle.kts') }}" >> "$GITHUB_OUTPUT"
#
#<<<<<<< HEAD
# # if gradle has new dependencies installed generate the new cache key
#      - name: Generate Gradle Cache Key
#        id: gradle-cache-key
#        run: |
#            echo "key=gradle-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/settings.gradle.kts') }}" >> "$GITHUB_OUTPUT"
#
#=======
#>>>>>>> abd80909b36f3e696ff4113794f19fecddc94d16
#      - name: Cache Gradle Dependencies
#        uses: actions/cache@v4
#        with:
#                path: |
#                  ~/.gradle/caches
#                  ~/.gradle/wrapper
#                key: ${{ steps.gradle-cache-key.outputs.key }}
#                restore-keys: |
#                  gradle-
#
#      - name: Build the app
#        run: ./gradlew clean assemble --no-daemon
#
#      - name: Run Flyway Validate
#        run: ./gradlew flywayValidate
