name: Flyway Migration Test

on:
  workflow_call:

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: food_ordering_system_db
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uadmin -padmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      FLYWAY_DB_URL: jdbc:mysql://127.0.0.1:3306/food_ordering_system_db?createDatabaseIfNotExist=true
      FLYWAY_DB_USER: admin
      FLYWAY_DB_PASSWORD: admin

    steps:
      - name: checkout code to the runner
        uses: actions/checkout@v4

      - name: setup java and gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Flyway Migrate
        run: ./gradlew flywayMigrate

      - name: Run Flyway Info (Checkpoint)
        run: ./gradlew flywayInfo
