name: Flyway Migration test

on:
  workflow_call:
jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
            FLYWAY_DB_URL: jdbc:mysql://127.0.0.1:3306/food_ordering_system_db?createDatabaseIfNotExist=true
            FLYWAY_DB_USER: admin
            FLYWAY_DB_PASSWORD: admin
        ports:
          - 3306:3306
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: food_ordering_system_db
      DB_USER: admin
      DB_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: uat
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Run Flyway Migrate
        run: ./gradlew flywayMigrate

      - name: Run Flyway Info (Checkpoint)
        run: ./gradlew flywayInfo